#!/bin/bash
# Apache VirtualHost Template with variable replacement

if [ $# -lt 2 ]; then
  echo "Usage: $(basename $0) user domain [database]"
  exit 1
fi


user="$1"
domain="$2"
database="$3"

VHOSTDIR="/var/www/vhosts/$domain"
VHOSTPATH="/$VHOSTDIR/httpdocs"
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TEMPLATE="$SCRIPTDIR/vhost.template"
USERDIR="/home/$user"
USERLINKDIR="$USERDIR/$domain"
HOSTNAME=$(hostname)

## check if template file is here

if [ ! -f "$TEMPLATE" ]; then
  echo "Template $TEMPLATE does not exists" >&2
  exit 2
fi

## create vhost dir

if [ ! -d "$VHOSTPATH" ]; then
  echo "Web directory $path does not exists. Creating ...";
  
  # create VHOST dir
  mkdir -p $VHOSTPATH
  # give user ownership
  chown $user:ftpusers $VHOSTPATH
  # create link in user dir
  ln -s "$VHOSTPATH" "$USERLINKDIR"
else
  echo "Directory already exists: $VHOSTPATH"
  exit 3 
fi

APACHECONFDIR="/etc/httpd/conf.d"


# Escape slashes
doc_root=$(echo "$VHOSTPATH" | sed 's/\//\\\//g');

echo "Writing config to: $APACHECONFDIR/vhost_$domain.conf"

sed -e "s/{USER}/$user/g" -e "s/{DOC_ROOT}/$doc_root/g" -e "s/{DOMAIN}/$domain/g" -e "s/{SERVERNAME}/$HOSTNAME/g" $TEMPLATE > $APACHECONFDIR/vhost_$domain.conf
